apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  namespace: development # specify the namespace here
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-rc-pod
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
          protocol: TCP
